name: Build and Deploy to IIS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clean IIS folder
      run: Remove-Item -Recurse -Force "C:\inetpub\mywebapp\*" -ErrorAction SilentlyContinue

      - name: Build Docker image and extract publish folder
      run: |
        cd "${{ github.workspace }}"
        docker build --no-cache -t mywebapi-build .
        docker create --name extract-container mywebapi-build
        docker cp extract-container:/out/. "C:\inetpub\mywebapp"
        docker rm extract-container

    - name: Restart IIS
      run: iisreset
