name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image and extract publish folder
      run: |
        docker build -t mywebapi-build .
        docker create --name extract-container mywebapi-build
        docker cp extract-container:/out/. "C:\inetpub\mywebapp"
        docker rm extract-container

    - name: Restart IIS
      run: iisreset
